export const onboardingDummyData = [
  {
    id: '1',
    employeeName: 'John Doe',
    role: 'Software Engineer',
    startDate: '2024-06-01',
    onboardingStatus: 'Offer Accepted',
    email: 'john.doe@example.com',
    department: 'Engineering',
  },
  {
    id: '2',
    employeeName: 'Jane Smith',
    role: 'Product Manager',
    startDate: '2024-06-05',
    onboardingStatus: 'Data Submitted',
    email: 'jane.smith@example.com',
    department: 'Product',
  },
  {
    id: '3',
    employeeName: 'Michael Brown',
    role: 'UX Designer',
    startDate: '2024-06-10',
    onboardingStatus: 'HR Validation',
    email: 'michael.brown@example.com',
    department: 'Design',
  },
  {
    id: '4',
    employeeName: 'Emily Davis',
    role: 'Marketing Specialist',
    startDate: '2024-06-12',
    onboardingStatus: 'Asset Assigned',
    email: 'emily.davis@example.com',
    department: 'Marketing',
  },
  {
    id: '5',
    employeeName: 'Chris Wilson',
    role: 'Backend Developer',
    startDate: '2024-06-15',
    onboardingStatus: 'Offer Accepted',
    email: 'chris.wilson@example.com',
    department: 'Engineering',
  },
  {
    id: '6',
    employeeName: 'Sarah Johnson',
    role: 'Data Analyst',
    startDate: '2024-06-18',
    onboardingStatus: 'Data Submitted',
    email: 'sarah.johnson@example.com',
    department: 'Data',
  },
  {
    id: '7',
    employeeName: 'David Lee',
    role: 'DevOps Engineer',
    startDate: '2024-06-20',
    onboardingStatus: 'HR Validation',
    email: 'david.lee@example.com',
    department: 'Engineering',
  },
  {
    id: '8',
    employeeName: 'Laura White',
    role: 'HR Coordinator',
    startDate: '2024-06-22',
    onboardingStatus: 'Asset Assigned',
    email: 'laura.white@example.com',
    department: 'HR',
  },
  {
    id: '9',
    employeeName: 'Daniel Martin',
    role: 'Sales Representative',
    startDate: '2024-06-25',
    onboardingStatus: 'Offer Accepted',
    email: 'daniel.martin@example.com',
    department: 'Sales',
  },
  {
    id: '10',
    employeeName: 'Olivia Taylor',
    role: 'Content Writer',
    startDate: '2024-06-28',
    onboardingStatus: 'Data Submitted',
    email: 'olivia.taylor@example.com',
    department: 'Marketing',
  },
];
