export const offerStageDummyData = [
  {
    id: '1',
    applicantName: 'Alice Johnson',
    interviewType: 'Online',
    interviewDate: '2024-05-20',
    interviewTime: '10:00 AM',
    roleApplied: 'Senior Frontend Engineer',
    status: 'Accepted',
    email: 'alice.johnson@example.com',
  },
  {
    id: '2',
    applicantName: 'Bob Smith',
    interviewType: 'In-person',
    interviewDate: '2024-05-21',
    interviewTime: '02:00 PM',
    roleApplied: 'Product Manager',
    status: 'Rejected',
    email: 'bob.smith@example.com',
  },
  {
    id: '3',
    applicantName: 'Charlie Brown',
    interviewType: 'Online',
    interviewDate: '2024-05-18',
    interviewTime: '11:00 AM',
    roleApplied: 'UX Designer',
    status: 'Offer Sent',
    email: 'charlie.brown@example.com',
  },
  {
    id: '4',
    applicantName: 'David Lee',
    interviewType: 'Phone',
    interviewDate: '2024-05-22',
    interviewTime: '09:30 AM',
    roleApplied: 'Backend Developer',
    status: 'Pending',
    email: 'david.lee@example.com',
  },
  {
    id: '5',
    applicantName: 'Eva Green',
    interviewType: 'Online',
    interviewDate: '2024-05-19',
    interviewTime: '04:00 PM',
    roleApplied: 'Marketing Specialist',
    status: 'Accepted',
    email: 'eva.green@example.com',
  },
  {
    id: '6',
    applicantName: 'Frank White',
    interviewType: 'In-person',
    interviewDate: '2024-05-23',
    interviewTime: '01:00 PM',
    roleApplied: 'Sales Representative',
    status: 'Rejected',
    email: 'frank.white@example.com',
  },
  {
    id: '7',
    applicantName: 'Grace Hall',
    interviewType: 'Online',
    interviewDate: '2024-05-24',
    interviewTime: '10:30 AM',
    roleApplied: 'Data Analyst',
    status: 'Offer Sent',
    email: 'grace.hall@example.com',
  },
  {
    id: '8',
    applicantName: 'Henry Ford',
    interviewType: 'In-person',
    interviewDate: '2024-05-25',
    interviewTime: '11:00 AM',
    roleApplied: 'HR Coordinator',
    status: 'Pending',
    email: 'henry.ford@example.com',
  },
  {
    id: '9',
    applicantName: 'Ivy Wilson',
    interviewType: 'Online',
    interviewDate: '2024-05-26',
    interviewTime: '03:00 PM',
    roleApplied: 'Content Writer',
    status: 'Accepted',
    email: 'ivy.wilson@example.com',
  },
  {
    id: '10',
    applicantName: 'Jack King',
    interviewType: 'Phone',
    interviewDate: '2024-05-27',
    interviewTime: '02:30 PM',
    roleApplied: 'Customer Support',
    status: 'Offer Sent',
    email: 'jack.king@example.com',
  },
];
