export const assetManagementDummyData = [
  {
    id: '1',
    employeeName: 'Nathaniel Desire',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb -12-2025',
    status: 'In Progress',
    email: 'nathaniel.desire@example.com',
  },
  {
    id: '2',
    employeeName: 'Femi Johnson',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb -12-2025',
    status: 'Not Started',
    email: 'femi.johnson@example.com',
  },
  {
    id: '3',
    employeeName: 'David Ephraim',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb -12-2025',
    status: 'Completed',
    email: 'david.ephraim@example.com',
  },
  {
    id: '4',
    employeeName: 'Sarah Conner',
    role: 'Product Designer',
    department: 'Design',
    startDate: 'Feb -14-2025',
    status: 'In Progress',
    email: 'sarah.conner@example.com',
  },
  {
    id: '5',
    employeeName: 'Michael Smith',
    role: 'Product Manager',
    department: 'Product',
    startDate: 'Feb -15-2025',
    status: 'Not Started',
    email: 'michael.smith@example.com',
  },
  {
    id: '6',
    employeeName: 'Jessica Doe',
    role: 'Marketing Lead',
    department: 'Marketing',
    startDate: 'Feb -16-2025',
    status: 'Completed',
    email: 'jessica.doe@example.com',
  },
  {
    id: '7',
    employeeName: 'Robert Brown',
    role: 'DevOps Engineer',
    department: 'Engineering',
    startDate: 'Feb -17-2025',
    status: 'In Progress',
    email: 'robert.brown@example.com',
  },
  {
    id: '8',
    employeeName: 'Emily White',
    role: 'Data Analyst',
    department: 'Data',
    startDate: 'Feb -18-2025',
    status: 'Not Started',
    email: 'emily.white@example.com',
  },
  {
    id: '9',
    employeeName: 'Chris Green',
    role: 'UX Researcher',
    department: 'Design',
    startDate: 'Feb -19-2025',
    status: 'Completed',
    email: 'chris.green@example.com',
  },
  {
    id: '10',
    employeeName: 'Olivia Black',
    role: 'HR Specialist',
    department: 'HR',
    startDate: 'Feb -20-2025',
    status: 'In Progress',
    email: 'olivia.black@example.com',
  },
];
