export const interviewSchedulesDummyData = [
  {
    id: '1',
    applicantName: 'Alice Johnson',
    interviewType: 'Online',
    interviewDate: '2024-05-20',
    interviewTime: '10:00 AM',
    roleApplied: 'Senior Frontend Engineer',
    status: 'Upcoming',
    email: 'alice.johnson@example.com',
    phone: '+1 (555) 123-4567',
    location: 'New York, USA',
  },
  {
    id: '2',
    applicantName: 'Bob Smith',
    interviewType: 'In-person',
    interviewDate: '2024-05-21',
    interviewTime: '02:00 PM',
    roleApplied: 'Product Manager',
    status: 'Pending',
    email: 'bob.smith@example.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, USA',
  },
  {
    id: '3',
    applicantName: 'Charlie Brown',
    interviewType: 'Online',
    interviewDate: '2024-05-18',
    interviewTime: '11:00 AM',
    roleApplied: 'UX Designer',
    status: 'Completed',
    email: 'charlie.brown@example.com',
    phone: '+1 (555) 345-6789',
    location: 'Austin, USA',
  },
  {
    id: '4',
    applicantName: 'David Lee',
    interviewType: 'Phone',
    interviewDate: '2024-05-22',
    interviewTime: '09:30 AM',
    roleApplied: 'Backend Developer',
    status: 'Upcoming',
    email: 'david.lee@example.com',
    phone: '+1 (555) 456-7890',
    location: 'Seattle, USA',
  },
  {
    id: '5',
    applicantName: 'Eva Green',
    interviewType: 'Online',
    interviewDate: '2024-05-19',
    interviewTime: '04:00 PM',
    roleApplied: 'Marketing Specialist',
    status: 'Completed',
    email: 'eva.green@example.com',
    phone: '+1 (555) 567-8901',
    location: 'Boston, USA',
  },
  {
    id: '6',
    applicantName: 'Frank White',
    interviewType: 'In-person',
    interviewDate: '2024-05-23',
    interviewTime: '01:00 PM',
    roleApplied: 'Sales Representative',
    status: 'Pending',
    email: 'frank.white@example.com',
    phone: '+1 (555) 678-9012',
    location: 'Chicago, USA',
  },
  {
    id: '7',
    applicantName: 'Grace Hall',
    interviewType: 'Online',
    interviewDate: '2024-05-24',
    interviewTime: '10:30 AM',
    roleApplied: 'Data Analyst',
    status: 'Upcoming',
    email: 'grace.hall@example.com',
    phone: '+1 (555) 789-0123',
    location: 'Denver, USA',
  },
  {
    id: '8',
    applicantName: 'Henry Ford',
    interviewType: 'In-person',
    interviewDate: '2024-05-25',
    interviewTime: '11:00 AM',
    roleApplied: 'HR Coordinator',
    status: 'Pending',
    email: 'henry.ford@example.com',
    phone: '+1 (555) 890-1234',
    location: 'Miami, USA',
  },
  {
    id: '9',
    applicantName: 'Ivy Wilson',
    interviewType: 'Online',
    interviewDate: '2024-05-26',
    interviewTime: '03:00 PM',
    roleApplied: 'Content Writer',
    status: 'Completed',
    email: 'ivy.wilson@example.com',
    phone: '+1 (555) 901-2345',
    location: 'Portland, USA',
  },
  {
    id: '10',
    applicantName: 'Jack King',
    interviewType: 'Phone',
    interviewDate: '2024-05-27',
    interviewTime: '02:30 PM',
    roleApplied: 'Customer Support',
    status: 'Upcoming',
    email: 'jack.king@example.com',
    phone: '+1 (555) 012-3456',
    location: 'Atlanta, USA',
  },
];
