export const hrValidationDummyData = [
  {
    id: '1',
    employeeName: 'Nathaniel Desire',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb 12, 2025',
    status: 'Pending',
    email: 'nathaniel.desire@example.com',
    personalInfo: {
      name: 'Nathaniel Desire',
      email: 'nathaniel.desire@example.com',
      phone: '+234 81 2345 6789',
      gender: 'Male',
      dob: 'May 12, 1995',
      employeeId: 'EMP-001',
      jobTitle: 'Senior Software Engineer',
      department: 'Engineering',
      employmentType: 'Full Time',
      address: 'Lagos, Nigeria',
      state: 'Lagos',
      lineManager: 'Hammed Adetunji',
    },
    bankInfo: {
      bankName: 'First Bank Plc',
      accountName: 'Nathaniel Desire',
      accountNumber: '**** **** 4567',
      salaryAmount: '₦450,000.00',
      taxId: 'TIN-12345678',
      bvn: '12345678901',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
      { name: 'Tax_Clearance_Certificate.pdf', type: 'Tax' },
    ],
  },
  {
    id: '2',
    employeeName: 'Femi Johnson',
    role: 'Marketing Specialist',
    department: 'Marketing',
    startDate: 'May 12, 2025',
    status: 'Needs Correction',
    email: 'femi.johnson@gmail.com',
    personalInfo: {
      name: 'Femi Johnson',
      email: 'femi.johnson@gmail.com',
      phone: '+234 90 1234 5678',
      gender: 'Female',
      dob: 'May 12, 2000',
      employeeId: 'EMP-002',
      jobTitle: 'Marketing Specialist',
      department: 'Marketing',
      employmentType: 'Full Time',
      address: 'Lagos, Nigeria',
      state: 'Lagos',
      lineManager: 'Hammed Adetunji',
    },
    bankInfo: {
      bankName: 'First Bank Plc',
      accountName: 'Femi Johnson',
      accountNumber: '**** **** 4567',
      salaryAmount: '₦350,000.00',
      taxId: 'TIN-23456789',
      bvn: '23456789012',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
  {
    id: '3',
    employeeName: 'David Ephraim',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb 12, 2025',
    status: 'Validated',
    email: 'david.ephraim@example.com',
    personalInfo: {
      name: 'David Ephraim',
      email: 'david.ephraim@example.com',
      phone: '+234 70 9876 5432',
      gender: 'Male',
      dob: 'Jun 15, 1992',
      employeeId: 'EMP-003',
      jobTitle: 'Senior Software Engineer',
      department: 'Engineering',
      employmentType: 'Full Time',
      address: 'Abuja, Nigeria',
      state: 'FCT',
      lineManager: 'Sarah Connor',
    },
    bankInfo: {
      bankName: 'GTBank',
      accountName: 'David Ephraim',
      accountNumber: '**** **** 1234',
      salaryAmount: '₦550,000.00',
      taxId: 'TIN-87654321',
      bvn: '98765432109',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
    ],
  },
  {
    id: '4',
    employeeName: 'Amara Okafor',
    role: 'HR Business Partner',
    department: 'Human Resources',
    startDate: 'Mar 3, 2025',
    status: 'Pending',
    email: 'amara.okafor@example.com',
    personalInfo: {
      name: 'Amara Okafor',
      email: 'amara.okafor@example.com',
      phone: '+234 80 3456 7890',
      gender: 'Female',
      dob: 'Aug 20, 1993',
      employeeId: 'EMP-004',
      jobTitle: 'HR Business Partner',
      department: 'Human Resources',
      employmentType: 'Full Time',
      address: 'Port Harcourt, Nigeria',
      state: 'Rivers',
      lineManager: 'Chioma Nwosu',
    },
    bankInfo: {
      bankName: 'Zenith Bank',
      accountName: 'Amara Okafor',
      accountNumber: '**** **** 8901',
      salaryAmount: '₦480,000.00',
      taxId: 'TIN-34567890',
      bvn: '34567890123',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
  {
    id: '5',
    employeeName: 'Chukwuemeka Nwosu',
    role: 'Financial Analyst',
    department: 'Finance',
    startDate: 'Jan 20, 2025',
    status: 'Validated',
    email: 'chukwuemeka.nwosu@example.com',
    personalInfo: {
      name: 'Chukwuemeka Nwosu',
      email: 'chukwuemeka.nwosu@example.com',
      phone: '+234 81 9012 3456',
      gender: 'Male',
      dob: 'Nov 5, 1990',
      employeeId: 'EMP-005',
      jobTitle: 'Financial Analyst',
      department: 'Finance',
      employmentType: 'Full Time',
      address: 'Enugu, Nigeria',
      state: 'Enugu',
      lineManager: 'Blessing Adeyemi',
    },
    bankInfo: {
      bankName: 'Access Bank',
      accountName: 'Chukwuemeka Nwosu',
      accountNumber: '**** **** 2345',
      salaryAmount: '₦520,000.00',
      taxId: 'TIN-45678901',
      bvn: '45678901234',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
      { name: 'Tax_Clearance_Certificate.pdf', type: 'Tax' },
    ],
  },
  {
    id: '6',
    employeeName: 'Blessing Adeyemi',
    role: 'Product Manager',
    department: 'Product',
    startDate: 'Apr 1, 2025',
    status: 'Needs Correction',
    email: 'blessing.adeyemi@example.com',
    personalInfo: {
      name: 'Blessing Adeyemi',
      email: 'blessing.adeyemi@example.com',
      phone: '+234 90 5678 9012',
      gender: 'Female',
      dob: 'Mar 14, 1991',
      employeeId: 'EMP-006',
      jobTitle: 'Product Manager',
      department: 'Product',
      employmentType: 'Full Time',
      address: 'Ibadan, Nigeria',
      state: 'Oyo',
      lineManager: 'Gideon Eze',
    },
    bankInfo: {
      bankName: 'UBA',
      accountName: 'Blessing Adeyemi',
      accountNumber: '**** **** 3456',
      salaryAmount: '₦600,000.00',
      taxId: 'TIN-56789012',
      bvn: '56789012345',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
  {
    id: '7',
    employeeName: 'Tunde Balogun',
    role: 'DevOps Engineer',
    department: 'Engineering',
    startDate: 'Feb 25, 2025',
    status: 'Pending',
    email: 'tunde.balogun@example.com',
    personalInfo: {
      name: 'Tunde Balogun',
      email: 'tunde.balogun@example.com',
      phone: '+234 70 6789 0123',
      gender: 'Male',
      dob: 'Jul 30, 1994',
      employeeId: 'EMP-007',
      jobTitle: 'DevOps Engineer',
      department: 'Engineering',
      employmentType: 'Full Time',
      address: 'Lagos, Nigeria',
      state: 'Lagos',
      lineManager: 'Nathaniel Desire',
    },
    bankInfo: {
      bankName: 'Kuda Bank',
      accountName: 'Tunde Balogun',
      accountNumber: '**** **** 4567',
      salaryAmount: '₦430,000.00',
      taxId: 'TIN-67890123',
      bvn: '67890123456',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
  {
    id: '8',
    employeeName: 'Ngozi Eze',
    role: 'UI/UX Designer',
    department: 'Design',
    startDate: 'Mar 17, 2025',
    status: 'Validated',
    email: 'ngozi.eze@example.com',
    personalInfo: {
      name: 'Ngozi Eze',
      email: 'ngozi.eze@example.com',
      phone: '+234 81 7890 1234',
      gender: 'Female',
      dob: 'Sep 2, 1997',
      employeeId: 'EMP-008',
      jobTitle: 'UI/UX Designer',
      department: 'Design',
      employmentType: 'Full Time',
      address: 'Kano, Nigeria',
      state: 'Kano',
      lineManager: 'Blessing Adeyemi',
    },
    bankInfo: {
      bankName: 'Sterling Bank',
      accountName: 'Ngozi Eze',
      accountNumber: '**** **** 5678',
      salaryAmount: '₦380,000.00',
      taxId: 'TIN-78901234',
      bvn: '78901234567',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'Portfolio.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
  {
    id: '9',
    employeeName: 'Emmanuel Obi',
    role: 'Data Scientist',
    department: 'Engineering',
    startDate: 'May 5, 2025',
    status: 'Pending',
    email: 'emmanuel.obi@example.com',
    personalInfo: {
      name: 'Emmanuel Obi',
      email: 'emmanuel.obi@example.com',
      phone: '+234 90 8901 2345',
      gender: 'Male',
      dob: 'Feb 18, 1996',
      employeeId: 'EMP-009',
      jobTitle: 'Data Scientist',
      department: 'Engineering',
      employmentType: 'Full Time',
      address: 'Benin City, Nigeria',
      state: 'Edo',
      lineManager: 'David Ephraim',
    },
    bankInfo: {
      bankName: 'Opay',
      accountName: 'Emmanuel Obi',
      accountNumber: '**** **** 6789',
      salaryAmount: '₦500,000.00',
      taxId: 'TIN-89012345',
      bvn: '89012345678',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
  {
    id: '10',
    employeeName: 'Kemi Adewale',
    role: 'Customer Success Manager',
    department: 'Operations',
    startDate: 'Jan 6, 2025',
    status: 'Needs Correction',
    email: 'kemi.adewale@example.com',
    personalInfo: {
      name: 'Kemi Adewale',
      email: 'kemi.adewale@example.com',
      phone: '+234 80 9012 3456',
      gender: 'Female',
      dob: 'Dec 25, 1992',
      employeeId: 'EMP-010',
      jobTitle: 'Customer Success Manager',
      department: 'Operations',
      employmentType: 'Full Time',
      address: 'Lagos, Nigeria',
      state: 'Lagos',
      lineManager: 'Amara Okafor',
    },
    bankInfo: {
      bankName: 'Fidelity Bank',
      accountName: 'Kemi Adewale',
      accountNumber: '**** **** 7890',
      salaryAmount: '₦410,000.00',
      taxId: 'TIN-90123456',
      bvn: '90123456789',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
    ],
  },
];
