export const hrValidationDummyData = [
  {
    id: '1',
    employeeName: 'Nathaniel Desire',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb -12-2025',
    status: 'Pending',
    email: 'nathaniel.desire@example.com',
    personalInfo: {
      name: 'Nathaniel Desire',
      email: 'nathaniel.desire@example.com',
      phone: '+234 81 2345 6789',
      gender: 'Male',
      dob: 'May 12, 1995',
      employeeId: 'EMP-001',
      jobTitle: 'Senior Software Engineer',
      department: 'Engineering',
      employmentType: 'Full Time',
      address: 'Lagos, Nigeria',
      state: 'Lagos',
      lineManager: 'Hammed Adetunji',
    },
    bankInfo: {
      bankName: 'First Bank Plc',
      accountName: 'Nathaniel Desire',
      accountNumber: '**** **** 4567',
      salaryAmount: '₦450,000.00',
      taxId: 'TIN-12345678',
      bvn: '12345678901',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
      { name: 'Tax_Clearance_Certificate.pdf', type: 'Tax' },
    ],
  },
  {
    id: '2',
    employeeName: 'Femi Johnson',
    role: 'Marketing Specialist',
    department: 'Marketing',
    startDate: 'May 12, 2024',
    status: 'Needs Correction',
    email: 'femi.johnson@gmail.com',
    personalInfo: {
      name: 'Femi Johnson',
      email: 'femi.johnson@gmail.com',
      phone: '+234 90 1234 5678',
      gender: 'Female',
      dob: 'May 12, 2004',
      employeeId: '34537-721',
      jobTitle: 'Marketing Specialist',
      department: 'Engineering Dept.',
      employmentType: 'Full Time',
      address: 'Lagos, Nigeria',
      state: 'Lagos',
      lineManager: 'Hammed Adetunji',
    },
    bankInfo: {
      bankName: 'First Bank Plc',
      accountName: 'Femi Johnson',
      accountNumber: '**** **** 4567',
      salaryAmount: '₦4,500,000',
      taxId: '123-45-6789',
      bvn: '123-45-6789',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
      { name: 'Offer_Letter.pdf', type: 'Offer Letter' },
      { name: 'Tax_Clearance_Certificate.pdf', type: 'Tax' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
    ],
  },
  {
    id: '3',
    employeeName: 'David Ephraim',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    startDate: 'Feb -12-2025',
    status: 'Validated',
    email: 'david.ephraim@example.com',
    personalInfo: {
      name: 'David Ephraim',
      email: 'david.ephraim@example.com',
      phone: '+234 70 9876 5432',
      gender: 'Male',
      dob: 'Jun 15, 1992',
      employeeId: 'EMP-003',
      jobTitle: 'Senior Software Engineer',
      department: 'Engineering',
      employmentType: 'Full Time',
      address: 'Abuja, Nigeria',
      state: 'FCT',
      lineManager: 'Sarah Connor',
    },
    bankInfo: {
      bankName: 'GTBank',
      accountName: 'David Ephraim',
      accountNumber: '**** **** 1234',
      salaryAmount: '₦550,000.00',
      taxId: 'TIN-87654321',
      bvn: '98765432109',
    },
    documents: [
      { name: 'National_ID.pdf', type: 'Personal' },
      { name: 'Employment_Contract.pdf', type: 'Contract of Employment' },
      { name: 'University_Degree.pdf', type: 'Certificate' },
    ],
  },
  // ... Keep other simple records for list view purposes or duplicate structure if needed
];
